"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArchitectureDiagram = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const framer_motion_1 = require("framer-motion");
const lucide_react_1 = require("lucide-react");
const ArchitectureDiagram = ({ nodes, links, title, description }) => {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "w-full space-y-8 py-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-10 h-10 rounded-xl bg-indigo-500/20 flex items-center justify-center text-indigo-400", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Layers, { size: 20 }) }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-xl font-bold", children: title || 'Architectural Flow' }), (0, jsx_runtime_1.jsx)("p", { className: "text-[10px] text-slate-500 uppercase tracking-widest leading-none mt-1", children: "Cognitive Architecture Diagram" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 px-3 py-1 bg-slate-800 rounded-full border border-slate-700", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Activity, { size: 12, className: "text-emerald-400" }), (0, jsx_runtime_1.jsx)("span", { className: "text-[9px] font-black uppercase text-slate-400", children: "Animated Pipeline" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "relative bg-slate-900 shadow-2xl rounded-3xl border border-slate-800 p-10 overflow-hidden flex flex-wrap justify-center gap-12 items-center", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 bg-grid-slate-800 opacity-20", style: { backgroundSize: '20px 20px', backgroundImage: 'radial-gradient(circle, #1e293b 1px, transparent 1px)' } }), nodes.map((node, i) => ((0, jsx_runtime_1.jsxs)(react_1.default.Fragment, { children: [(0, jsx_runtime_1.jsxs)(framer_motion_1.motion.div, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { delay: i * 0.1 }, className: "relative z-10 flex flex-col items-center gap-3 group", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-20 h-20 rounded-2xl flex items-center justify-center text-white transition-all duration-500 border border-white/5 shadow-2xl", style: {
                                            backgroundColor: node.color,
                                            boxShadow: `0 0 40px ${node.color}20`
                                        }, children: node.icon ? (0, jsx_runtime_1.jsx)(node.icon, { size: 32 }) : (0, jsx_runtime_1.jsx)(lucide_react_1.GitBranch, { size: 32 }) }), (0, jsx_runtime_1.jsx)("p", { className: "text-[10px] font-black uppercase tracking-widest text-slate-400 group-hover:text-white transition-colors", children: node.label })] }), i < nodes.length - 1 && ((0, jsx_runtime_1.jsxs)(framer_motion_1.motion.div, { initial: { opacity: 0, width: 0 }, animate: { opacity: 1, width: 40 }, transition: { delay: i * 0.15 }, className: "flex items-center", children: [(0, jsx_runtime_1.jsx)("div", { className: "h-px bg-gradient-to-r from-transparent via-slate-600 to-transparent flex-1" }), (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { size: 16, className: "text-slate-600" })] }))] }, node.id)))] }), description && ((0, jsx_runtime_1.jsxs)("div", { className: "p-5 bg-indigo-500/5 border border-indigo-500/20 rounded-2xl flex items-start gap-4", children: [(0, jsx_runtime_1.jsx)("div", { className: "bg-indigo-600/20 p-2 rounded-lg text-indigo-400", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Activity, { size: 20 }) }), (0, jsx_runtime_1.jsx)("p", { className: "text-xs text-slate-400 leading-relaxed font-medium", children: description })] }))] }));
};
exports.ArchitectureDiagram = ArchitectureDiagram;
//# sourceMappingURL=ArchitectureDiagram.js.map